### ISSUE TITLE
Beta release?

### ISSUE THREAD

**Issue by satta** [google/python_portpicker#26]
Just wanting to ask if 1.5.0b1 is a beta release and there will be an actual 1.5.0 eventually. I am the maintainer of portpicker in Debian and would like to know if I will need to ensure proper version order for future packages.

**Comment by gpshead** [comment]
I'll turn it into a 1.5.0 release shortly.

**Comment by satta** [comment]
Thanks -- then I did the right thing to make sure in packaging that the b1 version number sorts _before_ 1.5.0; this facilitates smooth automated updates. 👍🏻
